HDouss/jeometry

.github/workflows/merge-pr.yml

#7 add github workflow file to manage pr merging

---

.travis.yml

#10 switch to openjdk in travis file

---

jeometry-api/src/main/java/com/jeometry/twod/Shape.java
jeometry-api/src/main/java/com/jeometry/twod/style/Dash.java
jeometry-api/src/main/java/com/jeometry/twod/style/Fill.java
jeometry-api/src/main/java/com/jeometry/twod/style/Stroke.java
jeometry-api/src/main/java/com/jeometry/twod/style/Style.java
jeometry-api/src/main/java/com/jeometry/twod/style/impl/DefaultStyle.java
jeometry-api/src/main/java/com/jeometry/twod/style/impl/package-info.java
jeometry-api/src/main/java/com/jeometry/twod/style/package-info.java
jeometry-api/src/test/java/com/jeometry/twod/ShapeTest.java
jeometry-api/src/test/java/com/jeometry/twod/style/impl/DefaultStyleTest.java
jeometry-api/src/test/java/com/jeometry/twod/style/impl/package-info.java

Add stroke and fill styles to shapes. Not implemented yet:
* Default styles
* Styles usage in AWT rendering

#13 Add rendering styles to shapes

---

README.md

#15 Contribution and PR approval process documentation

---

jeometry-api/.gitattributes

#25 add gitattributes file to force checkout with unix eol

---

jeometry-api/src/main/java/com/jeometry/twod/style/impl/DefaultFill.java
jeometry-api/src/main/java/com/jeometry/twod/style/impl/DefaultStroke.java
jeometry-api/src/test/java/com/jeometry/twod/style/impl/DefaultStyleTest.java

#21 Default stroke and fill style classes

---

.gitattributes
jeometry-api/.gitattributes

#26 add ident to java files in gitattributes

---

README.md

#18 Milestones and release management documentation

---

jeometry-api/src/main/java/com/jeometry/twod/style/impl/DefaultStroke.java
jeometry-api/src/main/java/com/jeometry/twod/style/impl/FixedColorFill.java
jeometry-api/src/main/java/com/jeometry/twod/style/impl/FixedStroke.java
jeometry-api/src/main/java/com/jeometry/twod/style/impl/FixedStyle.java
jeometry-api/src/main/java/com/jeometry/twod/style/impl/TransparentFill.java
jeometry-api/src/test/java/com/jeometry/twod/style/impl/DefaultStrokeTest.java
jeometry-api/src/test/java/com/jeometry/twod/style/impl/DefaultStyleTest.java
jeometry-api/src/test/java/com/jeometry/twod/style/impl/TransparentFillTest.java

#35 Rename old default classes and create new ones

---

jeometry-double/src/main/java/com/jeometry/render/awt/style/AwtStroke.java
jeometry-double/src/main/java/com/jeometry/render/awt/style/package-info.java
jeometry-double/src/test/java/com/jeometry/render/awt/style/AwtStrokeTest.java
jeometry-double/src/test/java/com/jeometry/render/awt/style/package-info.java

#38 add AwtStroke class

---

README.md

#22 Document shape styles usage

---

jeometry-api/src/test/java/com/jeometry/twod/style/impl/FixedColorFillTest.java
jeometry-api/src/test/java/com/jeometry/twod/style/impl/FixedStrokeTest.java
jeometry-api/src/test/java/com/jeometry/twod/style/impl/FixedStyleTest.java

#37 add tests for FixedColorFill, FixedStroke and FixedStyle

---

README.md

#52 add line break before illustration

---

.github/workflows/release.yml

#54 setup env for headless environment

---

.github/workflows/release.yml

Resolving issue #56 : upload artifacts in release workflow to the github release.

#56 upload artifacts

---

aljebra/src/main/java/com/aljebra/matrix/VectorMatrix.java
aljebra/src/test/java/com/aljebra/matrix/VectorMatrixTest.java
jeometry-api/src/main/java/com/jeometry/twod/point/InLinePoint.java
jeometry-api/src/main/java/com/jeometry/twod/point/LineReflectionPoint.java
jeometry-api/src/main/java/com/jeometry/twod/ray/PtsRay.java
jeometry-api/src/test/java/com/jeometry/twod/point/HorPointTest.java
jeometry-api/src/test/java/com/jeometry/twod/point/InRayPointTest.java
jeometry-api/src/test/java/com/jeometry/twod/point/InSegPointTest.java
jeometry-api/src/test/java/com/jeometry/twod/point/MidSegPointTest.java
jeometry-api/src/test/java/com/jeometry/twod/point/OutsideLinePointTest.java
jeometry-api/src/test/java/com/jeometry/twod/point/YPointTest.java
jeometry-api/src/test/java/com/jeometry/twod/ray/AngleBisectorTest.java
jeometry-api/src/test/java/com/jeometry/twod/ray/PtDirRayTest.java
jeometry-api/src/test/java/com/jeometry/twod/scalar/SegmentLengthTest.java

Resolving issue #29 
Code coverage increased.
Some non relevant ToString lombok generation eliminated in: VectorMatrix, InLinePoint, LineReflectionPoint, PtsRay

#29 Increase test coverage

---

README.md

#24 update documentation

---

README.md

#60 update coveralls check requirements

---

aljebra/src/main/java/com/aljebra/field/impl/doubles/Dot.java
aljebra/src/main/java/com/aljebra/metric/InnerProduct.java
aljebra/src/main/java/com/aljebra/metric/angle/Acute.java
aljebra/src/main/java/com/aljebra/metric/angle/Complementary.java
aljebra/src/main/java/com/aljebra/metric/angle/Degrees.java
aljebra/src/main/java/com/aljebra/metric/angle/Flat.java
aljebra/src/main/java/com/aljebra/metric/angle/Obtuse.java
aljebra/src/main/java/com/aljebra/metric/angle/Right.java
aljebra/src/main/java/com/aljebra/metric/angle/Sum.java
aljebra/src/main/java/com/aljebra/metric/angle/Supplementary.java
aljebra/src/main/java/com/aljebra/metric/angle/Times.java
aljebra/src/main/java/com/aljebra/metric/angle/VectsDegrees.java
aljebra/src/main/java/com/aljebra/metric/vect/BisectorVect.java
aljebra/src/main/java/com/aljebra/metric/vect/RotateVect.java
aljebra/src/test/java/com/aljebra/field/impl/doubles/DotTest.java
aljebra/src/test/java/com/aljebra/metric/angle/AcuteTest.java
aljebra/src/test/java/com/aljebra/metric/angle/ComplementaryTest.java
aljebra/src/test/java/com/aljebra/metric/angle/DegreesTest.java
aljebra/src/test/java/com/aljebra/metric/angle/FlatTest.java
aljebra/src/test/java/com/aljebra/metric/angle/ObtuseTest.java
aljebra/src/test/java/com/aljebra/metric/angle/RightTest.java
aljebra/src/test/java/com/aljebra/metric/angle/SumTest.java
aljebra/src/test/java/com/aljebra/metric/angle/SupplementaryTest.java
aljebra/src/test/java/com/aljebra/metric/angle/TimesTest.java
aljebra/src/test/java/com/aljebra/metric/angle/VectsDegreesTest.java
aljebra/src/test/java/com/aljebra/metric/vect/RotateVectTest.java

#68 degrees no longer generic

---

aljebra/src/main/java/com/aljebra/scalar/condition/And.java
aljebra/src/main/java/com/aljebra/scalar/condition/Equals.java
aljebra/src/main/java/com/aljebra/scalar/condition/False.java
aljebra/src/main/java/com/aljebra/scalar/condition/Not.java
aljebra/src/main/java/com/aljebra/scalar/condition/Or.java
aljebra/src/main/java/com/aljebra/scalar/condition/Predicate.java
aljebra/src/main/java/com/aljebra/scalar/condition/Ternary.java
aljebra/src/main/java/com/aljebra/scalar/condition/True.java
aljebra/src/main/java/com/aljebra/vector/VectEquals.java
aljebra/src/test/java/com/aljebra/scalar/condition/AndTest.java
aljebra/src/test/java/com/aljebra/scalar/condition/EqualsTest.java
aljebra/src/test/java/com/aljebra/scalar/condition/FalseTest.java
aljebra/src/test/java/com/aljebra/scalar/condition/NotTest.java
aljebra/src/test/java/com/aljebra/scalar/condition/OrTest.java
aljebra/src/test/java/com/aljebra/scalar/condition/TernaryTest.java
aljebra/src/test/java/com/aljebra/scalar/condition/TrueTest.java
aljebra/src/test/java/com/aljebra/vector/VectEqualsTest.java
jeometry-api/src/main/java/com/jeometry/twod/circle/analytics/PointInCircle.java
jeometry-api/src/main/java/com/jeometry/twod/line/analytics/Equal.java
jeometry-api/src/main/java/com/jeometry/twod/line/analytics/Intersecting.java
jeometry-api/src/main/java/com/jeometry/twod/line/analytics/Parallel.java
jeometry-api/src/main/java/com/jeometry/twod/line/analytics/Perpendicular.java
jeometry-api/src/main/java/com/jeometry/twod/line/analytics/PointInLine.java
jeometry-api/src/main/java/com/jeometry/twod/line/analytics/Vertical.java

#69 Predicate is not genric anymore

---

aljebra/src/test/java/com/aljebra/scalar/ScalarTest.java
jeometry-api/src/main/java/com/jeometry/twod/RenderSupport.java
jeometry-double/src/main/java/com/jeometry/render/awt/Awt.java
jeometry-double/src/main/java/com/jeometry/render/awt/AwtDrawableSurface.java
jeometry-double/src/main/java/com/jeometry/render/awt/style/AwtStroke.java
jeometry-double/src/test/java/com/jeometry/render/awt/AwtTest.java
jeometry-double/src/test/java/com/jeometry/render/awt/style/AwtStrokeTest.java

#73 remove null usages

---

jeometry-double/src/main/java/com/jeometry/model/decimal/DblCircle.java
jeometry-double/src/main/java/com/jeometry/render/awt/AwtAngle.java
jeometry-double/src/main/java/com/jeometry/render/awt/AwtCircle.java
jeometry-double/src/main/java/com/jeometry/render/awt/AwtLine.java
jeometry-double/src/main/java/com/jeometry/render/awt/AwtPoint.java
jeometry-double/src/main/java/com/jeometry/render/awt/AwtRay.java
jeometry-double/src/main/java/com/jeometry/render/awt/AwtSegment.java
jeometry-double/src/main/java/com/jeometry/render/awt/AwtTransform.java
jeometry-double/src/main/java/com/jeometry/render/awt/AxisPaint.java
jeometry-double/src/test/java/com/jeometry/model/decimal/DblCircleTest.java
jeometry-double/src/test/java/com/jeometry/render/awt/AwtAngleTest.java
jeometry-double/src/test/java/com/jeometry/render/awt/AwtCircleTest.java
jeometry-double/src/test/java/com/jeometry/render/awt/AwtDrawableSurfaceTest.java
jeometry-double/src/test/java/com/jeometry/render/awt/AwtLineTest.java
jeometry-double/src/test/java/com/jeometry/render/awt/AwtPointTest.java
jeometry-double/src/test/java/com/jeometry/render/awt/AwtRayTest.java
jeometry-double/src/test/java/com/jeometry/render/awt/AwtSegmentTest.java
jeometry-double/src/test/java/com/jeometry/render/awt/AwtTest.java
jeometry-double/src/test/java/com/jeometry/render/awt/AwtTransformTest.java

#71 parametrize jeometry-double

---

aljebra/src/main/java/com/aljebra/metric/angle/Flat.java
aljebra/src/main/java/com/aljebra/metric/angle/Right.java
aljebra/src/test/java/com/aljebra/metric/angle/AcuteTest.java
aljebra/src/test/java/com/aljebra/metric/angle/ComplementaryTest.java
aljebra/src/test/java/com/aljebra/metric/angle/DegreesTest.java
aljebra/src/test/java/com/aljebra/metric/angle/ObtuseTest.java
aljebra/src/test/java/com/aljebra/metric/angle/SumTest.java
aljebra/src/test/java/com/aljebra/metric/angle/SupplementaryTest.java
aljebra/src/test/java/com/aljebra/metric/angle/TimesTest.java
aljebra/src/test/java/com/aljebra/metric/angle/VectsDegreesTest.java

#82 increase test coverage

---

README.md

#81 update documentation

---

aljebra/src/main/java/com/aljebra/field/impl/doubles/Dot.java
aljebra/src/main/java/com/aljebra/matrix/Sum.java
aljebra/src/main/java/com/aljebra/metric/angle/Sum.java
aljebra/src/main/java/com/aljebra/scalar/Add.java
aljebra/src/main/java/com/aljebra/scalar/Scalar.java
aljebra/src/main/java/com/aljebra/vector/Sum.java
aljebra/src/test/java/com/aljebra/field/impl/doubles/DotTest.java
aljebra/src/test/java/com/aljebra/matrix/SumTest.java
aljebra/src/test/java/com/aljebra/metric/angle/SumTest.java
aljebra/src/test/java/com/aljebra/scalar/AddTest.java
aljebra/src/test/java/com/aljebra/scalar/ScalarTest.java
aljebra/src/test/java/com/aljebra/vector/OppositeTest.java
aljebra/src/test/java/com/aljebra/vector/SumTest.java
jeometry-api/src/main/java/com/jeometry/twod/line/LineReflectionLine.java
jeometry-api/src/main/java/com/jeometry/twod/line/analytics/LinePointOrdinate.java
jeometry-api/src/main/java/com/jeometry/twod/line/analytics/PointInLine.java
jeometry-api/src/main/java/com/jeometry/twod/point/InCirclePoint.java
jeometry-api/src/main/java/com/jeometry/twod/point/InLinePoint.java
jeometry-api/src/main/java/com/jeometry/twod/point/InRayPoint.java
jeometry-api/src/main/java/com/jeometry/twod/point/InSegPoint.java
jeometry-api/src/main/java/com/jeometry/twod/point/MidSegPoint.java
jeometry-api/src/main/java/com/jeometry/twod/point/OutsideLinePoint.java
jeometry-api/src/main/java/com/jeometry/twod/point/PtReflectionPoint.java
jeometry-api/src/main/java/com/jeometry/twod/segment/PtVectSegment.java
jeometry-api/src/test/java/com/jeometry/twod/line/LineReflectionLineTest.java
jeometry-api/src/test/java/com/jeometry/twod/line/RayLineTest.java
jeometry-api/src/test/java/com/jeometry/twod/point/PtReflectionPointTest.java
jeometry-api/src/test/java/com/jeometry/twod/segment/PtVectSegmentTest.java

#85 add and sum warnings

---

aljebra/src/main/java/com/aljebra/field/impl/doubles/Dot.java
aljebra/src/main/java/com/aljebra/scalar/Multiplication.java
aljebra/src/main/java/com/aljebra/scalar/Scalar.java
aljebra/src/main/java/com/aljebra/vector/Times.java
aljebra/src/test/java/com/aljebra/field/impl/doubles/DotTest.java
aljebra/src/test/java/com/aljebra/matrix/TimesTest.java
aljebra/src/test/java/com/aljebra/scalar/MultiplicationTest.java
aljebra/src/test/java/com/aljebra/scalar/ScalarTest.java
aljebra/src/test/java/com/aljebra/vector/TimesTest.java
jeometry-api/src/main/java/com/jeometry/twod/line/analytics/Intercept.java
jeometry-api/src/main/java/com/jeometry/twod/line/analytics/LinePointOrdinate.java
jeometry-api/src/main/java/com/jeometry/twod/line/analytics/PointInLine.java

#86 Multiplication varargs suppression

---

aljebra/src/test/java/com/aljebra/scalar/ScalarTest.java
jeometry-api/src/main/java/com/jeometry/twod/line/PtReflectionLine.java
jeometry-api/src/main/java/com/jeometry/twod/line/PtsLine.java
jeometry-api/src/main/java/com/jeometry/twod/line/RandomLine.java
jeometry-api/src/main/java/com/jeometry/twod/line/VerticalLine.java
jeometry-api/src/main/java/com/jeometry/twod/segment/EndSegment.java
jeometry-api/src/main/java/com/jeometry/twod/segment/PtReflectionSegment.java
jeometry-api/src/main/java/com/jeometry/twod/segment/PtVectSegment.java
jeometry-api/src/main/java/com/jeometry/twod/segment/StartSegment.java
jeometry-api/src/test/java/com/jeometry/twod/segment/PtsSegmentTest.java

#91 Increase test coverage

---

aljebra/src/main/java/com/aljebra/field/impl/doubles/DblVect.java
aljebra/src/main/java/com/aljebra/matrix/FixedMatrix.java
aljebra/src/main/java/com/aljebra/matrix/Sum.java
aljebra/src/main/java/com/aljebra/matrix/Times.java
aljebra/src/main/java/com/aljebra/matrix/VectorMatrix.java
aljebra/src/main/java/com/aljebra/metric/vect/BisectorVect.java
aljebra/src/main/java/com/aljebra/metric/vect/Normalized.java
aljebra/src/main/java/com/aljebra/metric/vect/RotateVect.java
aljebra/src/main/java/com/aljebra/vector/FixedVector.java
aljebra/src/test/java/com/aljebra/field/impl/doubles/DblVectTest.java
aljebra/src/test/java/com/aljebra/field/impl/doubles/DotTest.java
aljebra/src/test/java/com/aljebra/matrix/FixedMatrixTest.java
aljebra/src/test/java/com/aljebra/matrix/SumTest.java
aljebra/src/test/java/com/aljebra/matrix/TimesTest.java
aljebra/src/test/java/com/aljebra/matrix/VectorMatrixTest.java
aljebra/src/test/java/com/aljebra/metric/vect/NormalizedTest.java
aljebra/src/test/java/com/aljebra/vector/FixedVectorTest.java
aljebra/src/test/java/com/aljebra/vector/OppositeTest.java
aljebra/src/test/java/com/aljebra/vector/VectEqualsTest.java
jeometry-api/src/main/java/com/jeometry/twod/point/LineIntersectPoint.java
jeometry-api/src/main/java/com/jeometry/twod/point/OutsideLinePoint.java
jeometry-api/src/main/java/com/jeometry/twod/point/XyPoint.java
jeometry-api/src/main/java/com/jeometry/twod/segment/CircleChord.java
jeometry-api/src/main/java/com/jeometry/twod/segment/CircleDiameter.java
jeometry-double/src/test/java/com/jeometry/render/awt/AwtAngleTest.java
jeometry-double/src/test/java/com/jeometry/render/awt/AwtCircleTest.java
jeometry-double/src/test/java/com/jeometry/render/awt/AwtLineTest.java
jeometry-double/src/test/java/com/jeometry/render/awt/AwtRayTest.java
jeometry-double/src/test/java/com/jeometry/render/awt/AwtSegmentTest.java
jeometry-double/src/test/java/com/jeometry/render/awt/AwtTest.java

#87 Fixed Vector list constructor

---

aljebra/src/main/java/com/aljebra/field/impl/doubles/DblMatrix.java
aljebra/src/main/java/com/aljebra/field/impl/doubles/Dot.java
aljebra/src/main/java/com/aljebra/matrix/FixedMatrix.java
aljebra/src/main/java/com/aljebra/matrix/TransposeMatrix.java
aljebra/src/main/java/com/aljebra/matrix/VectorMatrix.java
aljebra/src/main/java/com/aljebra/vector/Minus.java
aljebra/src/main/java/com/aljebra/vector/Sum.java
aljebra/src/main/java/com/aljebra/vector/Times.java
aljebra/src/test/java/com/aljebra/matrix/FixedMatrixTest.java
aljebra/src/test/java/com/aljebra/matrix/SumTest.java
aljebra/src/test/java/com/aljebra/matrix/TimesTest.java
aljebra/src/test/java/com/aljebra/matrix/TransposeMatrixTest.java
aljebra/src/test/java/com/aljebra/matrix/VectorMatrixTest.java
aljebra/src/test/java/com/aljebra/vector/MinusTest.java
aljebra/src/test/java/com/aljebra/vector/OppositeTest.java
aljebra/src/test/java/com/aljebra/vector/SumTest.java
aljebra/src/test/java/com/aljebra/vector/TimesTest.java
aljebra/src/test/java/com/aljebra/vector/VectEqualsTest.java

#88 fixedMatrix with iterable

---

aljebra/src/test/java/com/aljebra/field/impl/doubles/DecimalTest.java
aljebra/src/test/java/com/aljebra/field/impl/doubles/DotTest.java
aljebra/src/test/java/com/aljebra/matrix/FixedMatrixTest.java
aljebra/src/test/java/com/aljebra/matrix/SumTest.java
aljebra/src/test/java/com/aljebra/matrix/TimesTest.java
aljebra/src/test/java/com/aljebra/matrix/TransposeMatrixTest.java
aljebra/src/test/java/com/aljebra/matrix/VectorMatrixTest.java
aljebra/src/test/java/com/aljebra/metric/scalar/ProductTest.java
aljebra/src/test/java/com/aljebra/scalar/AddInverseTest.java
aljebra/src/test/java/com/aljebra/scalar/AddTest.java
aljebra/src/test/java/com/aljebra/scalar/BetweenTest.java
aljebra/src/test/java/com/aljebra/scalar/DiffTest.java
aljebra/src/test/java/com/aljebra/scalar/DifferentTest.java
aljebra/src/test/java/com/aljebra/scalar/DivisionTest.java
aljebra/src/test/java/com/aljebra/scalar/GreaterTest.java
aljebra/src/test/java/com/aljebra/scalar/LowerTest.java
aljebra/src/test/java/com/aljebra/scalar/MultInverseTest.java
aljebra/src/test/java/com/aljebra/scalar/MultiplicationTest.java
aljebra/src/test/java/com/aljebra/scalar/RandomTest.java
aljebra/src/test/java/com/aljebra/scalar/condition/EqualsTest.java
aljebra/src/test/java/com/aljebra/scalar/condition/NotTest.java
aljebra/src/test/java/com/aljebra/scalar/condition/TernaryTest.java
aljebra/src/test/java/com/aljebra/vector/MinusTest.java
aljebra/src/test/java/com/aljebra/vector/SumTest.java
aljebra/src/test/java/com/aljebra/vector/TimesTest.java
jeometry-api/src/test/java/com/jeometry/twod/point/XPointTest.java
jeometry-api/src/test/java/com/jeometry/twod/point/YPointTest.java

Rid of scalar mockings

---

aljebra/src/test/java/com/aljebra/matrix/SumTest.java
aljebra/src/test/java/com/aljebra/matrix/TimesTest.java
aljebra/src/test/java/com/aljebra/metric/angle/FlatTest.java
aljebra/src/test/java/com/aljebra/metric/angle/RightTest.java
aljebra/src/test/java/com/aljebra/metric/angle/VectsDegreesTest.java
aljebra/src/test/java/com/aljebra/metric/scalar/NormTest.java
aljebra/src/test/java/com/aljebra/metric/scalar/ProductTest.java
aljebra/src/test/java/com/aljebra/metric/vect/BisectorVectTest.java
aljebra/src/test/java/com/aljebra/metric/vect/RotateVectTest.java
aljebra/src/test/java/com/aljebra/vector/MinusTest.java
aljebra/src/test/java/com/aljebra/vector/SumTest.java
aljebra/src/test/java/com/aljebra/vector/TimesTest.java
jeometry-double/src/test/java/com/jeometry/model/decimal/DblCircleTest.java

Resolving issue #98 
No mocking objects implemented. Usage of FixedVector was enough.

#98 remove mocking vectors

---

aljebra/src/test/java/com/aljebra/metric/MockProduct.java
aljebra/src/test/java/com/aljebra/metric/angle/ComplementaryTest.java
aljebra/src/test/java/com/aljebra/metric/angle/FlatTest.java
aljebra/src/test/java/com/aljebra/metric/angle/ObtuseTest.java
aljebra/src/test/java/com/aljebra/metric/angle/RightTest.java
aljebra/src/test/java/com/aljebra/metric/angle/SumTest.java
aljebra/src/test/java/com/aljebra/metric/angle/SupplementaryTest.java
aljebra/src/test/java/com/aljebra/metric/angle/TimesTest.java
aljebra/src/test/java/com/aljebra/metric/angle/VectsDegreesTest.java
aljebra/src/test/java/com/aljebra/metric/scalar/NormTest.java
aljebra/src/test/java/com/aljebra/metric/scalar/ProductTest.java
aljebra/src/test/java/com/aljebra/vector/MinusTest.java

Resolving issue #101 
Implemented mocking object for InnerProduct with spying capabilities on the required methods.

#101 InnerProduct Mock object

---

aljebra/src/test/java/com/aljebra/field/SpyOrderedRandom.java
aljebra/src/test/java/com/aljebra/field/impl/doubles/DecimalTest.java

Resolving issue #100 
Implement OrderedRandom mock with spying capabilities (`verify` Mockito like), and with forcing value returns (`thenReturn` Mockito like)

#100 OrderedRandom mock

---

aljebra/src/test/java/com/aljebra/field/MkField.java
aljebra/src/test/java/com/aljebra/metric/scalar/NormTest.java
aljebra/src/test/java/com/aljebra/metric/scalar/ProductTest.java

Resolving issue #103 
Implemented a mock for MetricSpaceField that takes an InnerProduct to use in its constructor

#103 mocking metricspacefield

---

aljebra/src/test/java/com/aljebra/field/MkField.java
aljebra/src/test/java/com/aljebra/field/MkOrderedRandom.java
aljebra/src/test/java/com/aljebra/field/SpyField.java
aljebra/src/test/java/com/aljebra/field/impl/doubles/DecimalTest.java
aljebra/src/test/java/com/aljebra/metric/MkProduct.java
aljebra/src/test/java/com/aljebra/metric/angle/AcuteTest.java
aljebra/src/test/java/com/aljebra/metric/angle/ComplementaryTest.java
aljebra/src/test/java/com/aljebra/metric/angle/FlatTest.java
aljebra/src/test/java/com/aljebra/metric/angle/ObtuseTest.java
aljebra/src/test/java/com/aljebra/metric/angle/RightTest.java
aljebra/src/test/java/com/aljebra/metric/angle/SumTest.java
aljebra/src/test/java/com/aljebra/metric/angle/SupplementaryTest.java
aljebra/src/test/java/com/aljebra/metric/angle/TimesTest.java
aljebra/src/test/java/com/aljebra/metric/angle/VectsDegreesTest.java
aljebra/src/test/java/com/aljebra/metric/scalar/NormTest.java
aljebra/src/test/java/com/aljebra/metric/scalar/ProductTest.java
aljebra/src/test/java/com/aljebra/scalar/BetweenTest.java
aljebra/src/test/java/com/aljebra/scalar/GreaterTest.java
aljebra/src/test/java/com/aljebra/scalar/LowerTest.java

Resolving issue #105 
Implementing mock object for OrderedField
Renaming SpyOrderedRandom

#105 OrderedField mock and renaming some other mocks

---

jeometry-api/src/test/java/com/jeometry/twod/ray/AngleBisectorTest.java
jeometry-double/src/test/java/com/jeometry/render/awt/AwtAngleTest.java
jeometry-double/src/test/java/com/jeometry/render/awt/AwtLineTest.java
jeometry-double/src/test/java/com/jeometry/render/awt/AwtRayTest.java
jeometry-double/src/test/java/com/jeometry/twod/mock/SpyAngle.java
jeometry-double/src/test/java/com/jeometry/twod/mock/package-info.java

Resolving issue #107 
Implement Angle mock object capable of spying calls to methods.

#107 Angle mock object

---

jeometry-api/src/main/java/com/jeometry/twod/style/impl/StrokeStyle.java
jeometry-api/src/test/java/com/jeometry/twod/style/impl/StrokeStyleTest.java
jeometry-double/src/test/java/com/jeometry/render/awt/AwtAngleTest.java
jeometry-double/src/test/java/com/jeometry/render/awt/AwtCircleTest.java
jeometry-double/src/test/java/com/jeometry/render/awt/AwtDrawableSurfaceTest.java
jeometry-double/src/test/java/com/jeometry/render/awt/AwtLineTest.java
jeometry-double/src/test/java/com/jeometry/render/awt/AwtPointTest.java
jeometry-double/src/test/java/com/jeometry/render/awt/AwtRayTest.java
jeometry-double/src/test/java/com/jeometry/render/awt/AwtSegmentTest.java
jeometry-double/src/test/java/com/jeometry/render/awt/AwtTest.java
jeometry-double/src/test/java/com/jeometry/twod/mock/SpyCircle.java
jeometry-double/src/test/java/com/jeometry/twod/mock/SpyLine.java
jeometry-double/src/test/java/com/jeometry/twod/mock/SpyRay.java
jeometry-double/src/test/java/com/jeometry/twod/mock/SpySegment.java

Resolving issue #109 
Mocking objects for Line, Segment, Ray and Circle.

#109 Mock objects for Line segment, Ray and Circle

---

jeometry-api/src/main/java/com/jeometry/twod/line/Polygon.java
jeometry-api/src/main/java/com/jeometry/twod/line/PtReflectionPolyLine.java
jeometry-api/src/main/java/com/jeometry/twod/line/PtsPolyline.java
jeometry-api/src/test/java/com/jeometry/twod/line/PolygonTest.java
jeometry-api/src/test/java/com/jeometry/twod/line/PtReflectionPolyLineTest.java
jeometry-api/src/test/java/com/jeometry/twod/line/PtsPolylineTest.java

#121 PtsPolyline and Polygon unchecked warnings

---

jeometry-api/src/main/java/com/jeometry/twod/point/RandomPoint.java
jeometry-api/src/test/java/com/jeometry/twod/line/analytics/InterceptTest.java
jeometry-api/src/test/java/com/jeometry/twod/point/RandomPointTest.java

RandomPoint is necessarily non vertical

---

jeometry-api/src/main/java/com/jeometry/twod/line/VerticalLine.java
jeometry-api/src/test/java/com/jeometry/twod/line/VerticalLineTest.java

#151 VerticalLine passing by point

---

jeometry-api/src/test/java/com/jeometry/twod/line/RandomLineTest.java
jeometry-api/src/test/java/com/jeometry/twod/line/analytics/InterceptTest.java
jeometry-api/src/test/java/com/jeometry/twod/line/analytics/LinePointOrdinateTest.java
jeometry-api/src/test/java/com/jeometry/twod/line/analytics/ParallelTest.java
jeometry-api/src/test/java/com/jeometry/twod/line/analytics/SlopeTest.java
jeometry-api/src/test/java/com/jeometry/twod/line/analytics/VerticalTest.java
jeometry-api/src/test/java/com/jeometry/twod/point/DifferentPointTest.java
jeometry-api/src/test/java/com/jeometry/twod/point/VertPointTest.java

Resolving issue #148 
RandomLine is already non vertical after resolution of #147 
Add a test to guarantee non verticality
Simplify other tests

#148 RandomLine is not vertical

---

jeometry-api/src/main/java/com/jeometry/twod/line/analytics/Parallel.java
jeometry-api/src/main/java/com/jeometry/twod/style/impl/FixedStroke.java
jeometry-api/src/test/java/com/jeometry/twod/angle/PtsAngleTest.java
jeometry-api/src/test/java/com/jeometry/twod/circle/PtsCircleTest.java
jeometry-api/src/test/java/com/jeometry/twod/line/LineReflectionLineTest.java
jeometry-api/src/test/java/com/jeometry/twod/line/PerpBisectorTest.java
jeometry-api/src/test/java/com/jeometry/twod/line/PtReflectionLineTest.java
jeometry-api/src/test/java/com/jeometry/twod/line/VerticalLineTest.java
jeometry-api/src/test/java/com/jeometry/twod/line/analytics/PointInLineTest.java
jeometry-api/src/test/java/com/jeometry/twod/point/InRayPointTest.java
jeometry-api/src/test/java/com/jeometry/twod/point/InSegPointTest.java
jeometry-api/src/test/java/com/jeometry/twod/point/MidSegPointTest.java
jeometry-api/src/test/java/com/jeometry/twod/point/PtReflectionPointTest.java
jeometry-api/src/test/java/com/jeometry/twod/point/RandomPointTest.java
jeometry-api/src/test/java/com/jeometry/twod/style/impl/FixedStrokeTest.java

#134 Code improvements in jeometry-api

---

aljebra/src/test/java/com/aljebra/field/mock/FieldCalls.java
aljebra/src/test/java/com/aljebra/field/mock/MkAddition.java
aljebra/src/test/java/com/aljebra/field/mock/MkField.java
aljebra/src/test/java/com/aljebra/field/mock/MkMultiplication.java
aljebra/src/test/java/com/aljebra/field/mock/MkOrderedRandom.java
aljebra/src/test/java/com/aljebra/field/mock/SpyField.java
aljebra/src/test/java/com/aljebra/field/mock/SpyMetricSpace.java
aljebra/src/test/java/com/aljebra/scalar/mock/Scalars.java
aljebra/src/test/java/com/aljebra/scalar/mock/SpyScalar.java
jeometry-api/src/main/java/com/jeometry/twod/style/impl/StrokeStyle.java
jeometry-api/src/test/java/com/jeometry/twod/style/impl/StrokeStyleTest.java
jeometry-double/src/test/java/com/jeometry/twod/mock/SpyAngle.java
jeometry-double/src/test/java/com/jeometry/twod/mock/SpyCircle.java
jeometry-double/src/test/java/com/jeometry/twod/mock/SpyLine.java
jeometry-double/src/test/java/com/jeometry/twod/mock/SpyRay.java
jeometry-double/src/test/java/com/jeometry/twod/mock/SpySegment.java

#130 fix since version

---

aljebra/src/main/java/com/aljebra/field/MetricSpace.java
aljebra/src/main/java/com/aljebra/field/impl/doubles/DblVect.java
aljebra/src/main/java/com/aljebra/field/impl/doubles/Dot.java
aljebra/src/main/java/com/aljebra/matrix/FixedMatrix.java
aljebra/src/test/java/com/aljebra/field/impl/doubles/DblVectTest.java
aljebra/src/test/java/com/aljebra/field/impl/doubles/DecimalRandomTest.java
aljebra/src/test/java/com/aljebra/field/impl/doubles/DotTest.java
aljebra/src/test/java/com/aljebra/field/mock/MkOrderedRandom.java
aljebra/src/test/java/com/aljebra/matrix/TimesTest.java
aljebra/src/test/java/com/aljebra/scalar/DivisionTest.java
aljebra/src/test/java/com/aljebra/vector/FixedVectorTest.java
aljebra/src/test/java/com/aljebra/vector/OppositeTest.java
aljebra/src/test/java/com/aljebra/vector/VectEqualsTest.java

#133 Code improvements

---

jeometry-double/src/main/java/com/jeometry/render/Surface.java
jeometry-double/src/main/java/com/jeometry/render/Transform.java
jeometry-double/src/main/java/com/jeometry/render/awt/AbstractAwtPaint.java
jeometry-double/src/main/java/com/jeometry/render/awt/Awt.java
jeometry-double/src/main/java/com/jeometry/render/awt/AwtAngle.java
jeometry-double/src/main/java/com/jeometry/render/awt/AwtCircle.java
jeometry-double/src/main/java/com/jeometry/render/awt/AwtDrawableSurface.java
jeometry-double/src/main/java/com/jeometry/render/awt/AwtLine.java
jeometry-double/src/main/java/com/jeometry/render/awt/AwtRay.java
jeometry-double/src/main/java/com/jeometry/render/awt/AwtSegment.java
jeometry-double/src/main/java/com/jeometry/render/awt/AxisPaint.java
jeometry-double/src/main/java/com/jeometry/render/awt/MouseZoomTranslate.java
jeometry-double/src/test/java/com/jeometry/render/SurfaceTest.java
jeometry-double/src/test/java/com/jeometry/render/TransformTest.java
jeometry-double/src/test/java/com/jeometry/render/awt/AwtDrawableSurfaceTest.java
jeometry-double/src/test/java/com/jeometry/render/awt/AwtTest.java
jeometry-double/src/test/java/com/jeometry/render/awt/AxisPaintTest.java
jeometry-double/src/test/java/com/jeometry/render/package-info.java

#138 adjustements in double module

---

aljebra/src/main/java/com/aljebra/scalar/Scalar.java
aljebra/src/test/java/com/aljebra/scalar/ScalarTest.java
jeometry-api/src/main/java/com/jeometry/twod/line/analytics/LinePointOrdinate.java

Resolving issue #165 
Remove interface default methods and replace their usage with proper classes constructions.

#165 remove scalar interface default methods

---

aljebra/src/main/java/com/aljebra/metric/scalar/MetricScalar.java
aljebra/src/main/java/com/aljebra/metric/scalar/Norm.java
aljebra/src/main/java/com/aljebra/metric/scalar/Product.java
aljebra/src/main/java/com/aljebra/scalar/Between.java
aljebra/src/main/java/com/aljebra/scalar/Greater.java
aljebra/src/main/java/com/aljebra/scalar/Lower.java
aljebra/src/main/java/com/aljebra/scalar/OrderedScalar.java

Resolving issue #162 
Switch OrderedScalar and MetricScalar to abstract classes and get rid of interface default methods

#162 Switch OrderedScalar and MetricScalar to classes

---

aljebra/src/main/java/com/aljebra/field/impl/doubles/Dot.java
aljebra/src/main/java/com/aljebra/metric/InnerProduct.java

Resolving issue #164 
Remove `InnerProduct.resolve` method and modify calling method.

#164 Remove InnerProduct.resolve

---

jeometry-api/src/main/java/com/jeometry/twod/point/InLinePoint.java
jeometry-api/src/test/java/com/jeometry/twod/line/analytics/EqualTest.java
jeometry-api/src/test/java/com/jeometry/twod/point/InLinePointTest.java

Resolving #136 
New constructor with abscissa and behaviour testing.

#136 new constructor for InLinePoint

---

jeometry-double/src/main/java/com/jeometry/render/awt/TranslationButton.java
jeometry-double/src/main/java/com/jeometry/render/awt/ZoomInButton.java
jeometry-double/src/main/java/com/jeometry/render/awt/ZoomOutButton.java

Resolving issue #140 
Created two specialized classes for translation and zooming buttons

#140 Extract button classes

---

jeometry-api/src/main/java/com/jeometry/twod/Figure.java
jeometry-api/src/main/java/com/jeometry/twod/Shape.java
jeometry-api/src/test/java/com/jeometry/twod/ShapeTest.java

Resolving issue #143 
Makes shape name as an Optional.

#143 code improvements for Figure and Shape classes

---

aljebra/src/main/java/com/aljebra/vector/FixedVector.java
aljebra/src/test/java/com/aljebra/metric/angle/FlatTest.java
aljebra/src/test/java/com/aljebra/metric/angle/RightTest.java
aljebra/src/test/java/com/aljebra/metric/angle/VectsDegreesTest.java
aljebra/src/test/java/com/aljebra/metric/scalar/NormTest.java
aljebra/src/test/java/com/aljebra/metric/vect/NormalizedTest.java
aljebra/src/test/java/com/aljebra/vector/FixedVectorTest.java
jeometry-api/src/main/java/com/jeometry/twod/point/LineIntersectPoint.java
jeometry-api/src/main/java/com/jeometry/twod/point/XyPoint.java
jeometry-api/src/main/java/com/jeometry/twod/segment/CircleChord.java
jeometry-api/src/main/java/com/jeometry/twod/segment/CircleDiameter.java

Resolving issue #170 
Add more constructors and use them where applicable.

#170 more constructors for FixedVector

---

jeometry-api/src/main/java/com/jeometry/twod/style/impl/FillStyle.java
jeometry-api/src/test/java/com/jeometry/twod/style/impl/FillStyleTest.java

Resolving issue #145 
Adding a style only defined by a fill color.

#145 Fill style

---

aljebra/src/main/java/com/aljebra/field/AbstractField.java
aljebra/src/main/java/com/aljebra/field/Field.java
aljebra/src/main/java/com/aljebra/field/FieldAddition.java
aljebra/src/main/java/com/aljebra/field/FieldMultiplication.java
aljebra/src/main/java/com/aljebra/field/OrderedField.java
aljebra/src/main/java/com/aljebra/field/OrderedRandom.java
aljebra/src/main/java/com/aljebra/field/impl/doubles/DblMatrix.java
aljebra/src/main/java/com/aljebra/field/impl/doubles/DblVect.java
aljebra/src/main/java/com/aljebra/matrix/FixedMatrix.java
aljebra/src/main/java/com/aljebra/matrix/Sum.java
aljebra/src/main/java/com/aljebra/metric/vect/BisectorVect.java
aljebra/src/main/java/com/aljebra/scalar/condition/Not.java
aljebra/src/main/java/com/aljebra/vector/Opposite.java
aljebra/src/main/java/com/aljebra/vector/VectEquals.java
aljebra/src/test/java/com/aljebra/field/impl/doubles/DecimalTest.java
aljebra/src/test/java/com/aljebra/field/mock/MkOrderedRandom.java
aljebra/src/test/java/com/aljebra/metric/angle/DegreesTest.java
aljebra/src/test/java/com/aljebra/metric/angle/FlatTest.java
aljebra/src/test/java/com/aljebra/metric/angle/RightTest.java
aljebra/src/test/java/com/aljebra/scalar/BetweenTest.java
aljebra/src/test/java/com/aljebra/scalar/GreaterTest.java
aljebra/src/test/java/com/aljebra/scalar/LowerTest.java
aljebra/src/test/java/com/aljebra/scalar/RandomTest.java
aljebra/src/test/java/com/aljebra/scalar/mock/SpyScalar.java

#132 Fix javadoc in aljebra

---

jeometry-api/src/main/java/com/jeometry/twod/Figure.java
jeometry-api/src/main/java/com/jeometry/twod/angle/Angle.java
jeometry-api/src/main/java/com/jeometry/twod/arc/RadAngleArc.java
jeometry-api/src/main/java/com/jeometry/twod/line/PtReflectionPolyLine.java
jeometry-api/src/main/java/com/jeometry/twod/ray/PtDirRay.java
jeometry-api/src/main/java/com/jeometry/twod/segment/CircleDiameter.java
jeometry-api/src/main/java/com/jeometry/twod/style/Stroke.java
jeometry-api/src/main/java/com/jeometry/twod/style/Style.java
jeometry-api/src/main/java/com/jeometry/twod/style/impl/DefaultStyle.java
jeometry-api/src/main/java/com/jeometry/twod/style/impl/FixedStyle.java
jeometry-api/src/test/java/com/jeometry/twod/ray/PtsRayTest.java
jeometry-api/src/test/java/com/jeometry/twod/segment/RandomSegmentTest.java
jeometry-api/src/test/java/com/jeometry/twod/style/impl/DefaultStyleTest.java
jeometry-api/src/test/java/com/jeometry/twod/style/impl/FillStyleTest.java
jeometry-api/src/test/java/com/jeometry/twod/style/impl/FixedStyleTest.java
jeometry-api/src/test/java/com/jeometry/twod/style/impl/StrokeStyleTest.java
jeometry-double/src/main/java/com/jeometry/render/awt/AbstractAwtPaint.java
jeometry-double/src/main/java/com/jeometry/render/awt/AwtCircle.java
jeometry-double/src/test/java/com/jeometry/render/awt/AwtCircleTest.java

Resolving issue #135 
Fix javadoc issues in jeometry-api module.
Refactor to simplify RandomSegmentTest

#135 fix javadoc and test in jeometry-api

---

jeometry-double/src/main/java/com/jeometry/model/decimal/DblPoint.java
jeometry-double/src/main/java/com/jeometry/render/awt/AbstractAwtPaint.java
jeometry-double/src/main/java/com/jeometry/render/awt/Awt.java
jeometry-double/src/test/java/com/jeometry/model/decimal/DblPointTest.java
jeometry-double/src/test/java/com/jeometry/twod/mock/SpyAngle.java

Resolving issue #137
Fix/precise javadoc issues in jeometry-double module.

#137 Fix javadoc in jeometry-double

---

jeometry-api/src/main/java/com/jeometry/twod/line/analytics/PointInLine.java

Resolving issue #144 
Comparing with LinePointOrdinate in case of non vertical line

#144 simplify PointInLine predicate

---

jeometry-api/src/main/java/com/jeometry/twod/line/LineReflectionLine.java
jeometry-api/src/main/java/com/jeometry/twod/line/PtsLine.java

Resolving issue #180 
Simplify `LineReflectionLine` implementation by reflecting two points of the line.

#180 simplify LineReflectionLine

---

pom.xml

Resolving issue #183 
Update guava version to 24.1.1. No other modifications implied.

#183 update guava version

---

jeometry-double/src/main/java/com/jeometry/render/awt/AwtLine.java
jeometry-double/src/main/java/com/jeometry/render/awt/AwtRay.java

Resolving issue #139 
Drawing logic simplified by using the new constructor of InLinePoint.

#139 Simplify drawing logic in `AwtLine` and `AwtRay`

---

jeometry-double/src/main/java/com/jeometry/render/awt/AwtArc.java
jeometry-double/src/main/java/com/jeometry/render/awt/Painters.java
jeometry-double/src/test/java/com/jeometry/render/awt/AwtArcTest.java
jeometry-double/src/test/java/com/jeometry/twod/mock/SpyArc.java

Resolving issue #142 
Implement AWT Arc painter
Implement SpyArc for testing purpose
Add the new painter to the list of default painters

#142 implement arc awt renderer

---

jeometry-api/src/main/java/com/jeometry/twod/Figure.java
jeometry-api/src/main/java/com/jeometry/twod/RenderSupport.java
jeometry-api/src/main/java/com/jeometry/twod/Renderer.java
jeometry-api/src/main/java/com/jeometry/twod/Shape.java
jeometry-api/src/test/java/com/jeometry/twod/FigureTest.java
jeometry-api/src/test/java/com/jeometry/twod/RenderSupportTest.java
jeometry-api/src/test/java/com/jeometry/twod/ShapeTest.java
jeometry-double/src/main/java/com/jeometry/render/awt/AbstractAwtPaint.java
jeometry-double/src/main/java/com/jeometry/render/awt/AwtAngle.java
jeometry-double/src/main/java/com/jeometry/render/awt/AwtArc.java
jeometry-double/src/main/java/com/jeometry/render/awt/AwtCircle.java
jeometry-double/src/main/java/com/jeometry/render/awt/AwtDrawableSurface.java
jeometry-double/src/main/java/com/jeometry/render/awt/AwtLine.java
jeometry-double/src/main/java/com/jeometry/render/awt/AwtPoint.java
jeometry-double/src/main/java/com/jeometry/render/awt/AwtRay.java
jeometry-double/src/main/java/com/jeometry/render/awt/AwtSegment.java
jeometry-double/src/main/java/com/jeometry/render/awt/AxisPaint.java
jeometry-double/src/test/java/com/jeometry/render/awt/AwtAngleTest.java
jeometry-double/src/test/java/com/jeometry/render/awt/AwtArcTest.java
jeometry-double/src/test/java/com/jeometry/render/awt/AwtCircleTest.java
jeometry-double/src/test/java/com/jeometry/render/awt/AwtDrawableSurfaceTest.java
jeometry-double/src/test/java/com/jeometry/render/awt/AwtLineTest.java
jeometry-double/src/test/java/com/jeometry/render/awt/AwtPointTest.java
jeometry-double/src/test/java/com/jeometry/render/awt/AwtRayTest.java
jeometry-double/src/test/java/com/jeometry/render/awt/AwtSegmentTest.java
jeometry-double/src/test/java/com/jeometry/render/awt/AwtTest.java

Resolving issue #187 
Shape class is generic reflecting the type of the renderable.

#187 makes shape class generic

---

jeometry-api/src/main/java/com/jeometry/twod/Shape.java
jeometry-double/src/main/java/com/jeometry/render/awt/AbstractAwtPaint.java
jeometry-double/src/main/java/com/jeometry/render/awt/Awt.java
jeometry-double/src/main/java/com/jeometry/render/awt/AwtAngle.java
jeometry-double/src/main/java/com/jeometry/render/awt/AwtArc.java
jeometry-double/src/main/java/com/jeometry/render/awt/AwtCircle.java
jeometry-double/src/main/java/com/jeometry/render/awt/AwtDrawableSurface.java
jeometry-double/src/main/java/com/jeometry/render/awt/AwtLine.java
jeometry-double/src/main/java/com/jeometry/render/awt/AwtPoint.java
jeometry-double/src/main/java/com/jeometry/render/awt/AwtRay.java
jeometry-double/src/main/java/com/jeometry/render/awt/AwtSegment.java
jeometry-double/src/main/java/com/jeometry/render/awt/Painters.java
jeometry-double/src/test/java/com/jeometry/render/awt/AwtDrawableSurfaceTest.java
jeometry-double/src/test/java/com/jeometry/render/awt/AwtTest.java

Resolving issue #189
Get rid of casting in tha AWT painters logic

#189 no more casting in painters

---

aljebra/src/main/java/com/aljebra/field/impl/doubles/DblMatrix.java
aljebra/src/main/java/com/aljebra/field/impl/doubles/Dot.java
aljebra/src/main/java/com/aljebra/matrix/FixedMatrix.java
aljebra/src/main/java/com/aljebra/matrix/TransposeMatrix.java
aljebra/src/main/java/com/aljebra/matrix/VectorMatrix.java
aljebra/src/test/java/com/aljebra/field/impl/doubles/DblMatrixTest.java
aljebra/src/test/java/com/aljebra/matrix/TransposeMatrixTest.java
aljebra/src/test/java/com/aljebra/matrix/VectorMatrixTest.java

Resolving issue #194 
FixedMatrix is a final class.
Subclassing classes have a FixedMatrix field to which they delegate for method implementation

#194 FixedMatrix becomes final

---

jeometry-api/src/main/java/com/jeometry/twod/angle/PtsAngle.java
jeometry-api/src/main/java/com/jeometry/twod/circle/LineReflectionCircle.java
jeometry-api/src/main/java/com/jeometry/twod/circle/PtReflectionCircle.java
jeometry-api/src/main/java/com/jeometry/twod/line/LineReflectionLine.java
jeometry-api/src/main/java/com/jeometry/twod/line/Polygon.java
jeometry-api/src/main/java/com/jeometry/twod/line/analytics/LineAnalytics.java
jeometry-api/src/test/java/com/jeometry/twod/angle/EqualAngleTest.java
jeometry-api/src/test/java/com/jeometry/twod/angle/MeasureAngleTest.java
jeometry-api/src/test/java/com/jeometry/twod/arc/RadAngleArcTest.java
jeometry-api/src/test/java/com/jeometry/twod/circle/PtRadCircleTest.java
jeometry-api/src/test/java/com/jeometry/twod/line/IntersectingLineTest.java
jeometry-api/src/test/java/com/jeometry/twod/line/ParallelLineTest.java
jeometry-api/src/test/java/com/jeometry/twod/line/PerpBisectorTest.java
jeometry-api/src/test/java/com/jeometry/twod/line/PerpLineTest.java
jeometry-api/src/test/java/com/jeometry/twod/line/PtsPolylineTest.java
jeometry-api/src/test/java/com/jeometry/twod/line/RayLineTest.java
jeometry-api/src/test/java/com/jeometry/twod/line/SgtLineTest.java
jeometry-api/src/test/java/com/jeometry/twod/line/analytics/InterceptTest.java
jeometry-api/src/test/java/com/jeometry/twod/line/analytics/LinePointOrdinateTest.java
jeometry-api/src/test/java/com/jeometry/twod/line/analytics/ParallelTest.java
jeometry-api/src/test/java/com/jeometry/twod/line/analytics/PerpendicularTest.java
jeometry-api/src/test/java/com/jeometry/twod/line/analytics/SlopeTest.java
jeometry-api/src/test/java/com/jeometry/twod/line/analytics/VerticalTest.java

Resolving issue #196 
Increase test coverage

#196 increase test coverage

---

.github/workflows/merge-pr.yml
.github/workflows/release.yml

#201 fix version to 8

---

README.md

#199 add award badge
